SET CURRDIR=%~dp0
echo %CURRDIR%
IF NOT EXIST %CURRDIR%\JS_UIXML\UIXML\ENG(
mkdir "%CURRDIR%\JS_UIXML\UIXML\ENG"
)
IF NOT EXIST %CURRDIR%\JS_UIXML\Script\JS(
mkdir "%CURRDIR%\JS_UIXML\Script\JS"
)
SET TEMPDIR=%CURRDIR%\ROFC\MAIN\UIXML\ENG
IF EXIST %TEMPDIR%(
cd %TEMPDIR%
for /R %TEMPDIR% %%f in (*.xml) do copy %%f %CURRDIR%\JS_UIXML\UIXML\ENG
)
SET TEMPDIR=%CURRDIR%\ROFC\MAIN\JS
IF EXIST %TEMPDIR%(
cd %TEMPDIR%
for /R %TEMPDIR% %%f in (*.js) do copy %%f %CURRDIR%\JS_UIXML\Script\JS
)
SET TEMPDIR=%CURRDIR%\ROFC\OR\UIXML\ENG
IF EXIST %TEMPDIR%(
cd %TEMPDIR%
for /R %TEMPDIR% %%f in (*.xml) do copy %%f %CURRDIR%\JS_UIXML\UIXML\ENG
)
SET TEMPDIR=%CURRDIR%\ROFC\OR\JS
IF EXIST %TEMPDIR%(
cd %TEMPDIR%
for /R %TEMPDIR% %%f in (*.js) do copy %%f %CURRDIR%\JS_UIXML\Script\JS
)
SET TEMPDIR=%CURRDIR%\SMS\MAIN\UIXML\ENG
IF EXIST %TEMPDIR%(
cd %TEMPDIR%
for /R %TEMPDIR% %%f in (*.xml) do copy %%f %CURRDIR%\JS_UIXML\UIXML\ENG
)
SET TEMPDIR=%CURRDIR%\SMS\MAIN\JS
IF EXIST %TEMPDIR%(
cd %TEMPDIR%
for /R %TEMPDIR% %%f in (*.js) do copy %%f %CURRDIR%\JS_UIXML\Script\JS
)