SET AUTOBATCHSEQU=C:\Users\aarkrish\AppData\Roaming\Adobe\Acrobat\10.0\Sequences\PDF2WORD.sequ
SET AUTOBATCHFINAL=6
SET AUTOBATCHDEST=D:\Daily_PDF\PDF2WORD
SET AUTOBATCHALTPATH=%1
SET AUTOBATCHALTOUTPUTPATH=%2
SET AUTOBATCHNOPROGRESS=yes
"C:\Program Files (x86)\Adobe\Acrobat 10.0\Acrobat\Acrobat.exe" /n /h